In [1]:
import numpy as np
#计算幂和开根号
B =np.arange(3)
print(B)
print(np.exp(B))
print(np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [2]:
a = np.floor(10*np.random.random((3,4)))
print(a)
print(a.ravel()) #矩阵换成向量
a.shape = (6,2)
print(a)
print(a.T) #变化行列
#a.reshape(3,-1) 自动计算列

[[5. 6. 8. 5.]
 [9. 4. 4. 2.]
 [6. 8. 2. 2.]]
[5. 6. 8. 5. 9. 4. 4. 2. 6. 8. 2. 2.]
[[5. 6.]
 [8. 5.]
 [9. 4.]
 [4. 2.]
 [6. 8.]
 [2. 2.]]
[[5. 8. 9. 4. 6. 2.]
 [6. 5. 4. 2. 8. 2.]]


In [6]:
#矩阵拼接
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)
print(np.hstack((a,b)))
#横向拼接

[[2. 6.]
 [8. 5.]]
[[7. 4.]
 [4. 0.]]
[[2. 6. 7. 4.]
 [8. 5. 4. 0.]]


In [7]:
a = np.floor(10*np.random.random((2,2)))
b = np.floor(10*np.random.random((2,2)))
print(a)
print(b)
print(np.vstack((a,b)))
#纵向拼接

[[5. 9.]
 [0. 4.]]
[[3. 1.]
 [7. 7.]]
[[5. 9.]
 [0. 4.]
 [3. 1.]
 [7. 7.]]


In [10]:
#矩阵切分
a = np.floor(10*np.random.random((2,12)))
print(a)
print(np.hsplit(a,3))
print(np.hsplit(a,(3,4)))
a = np.floor(10*np.random.random((12,2)))
print(a)
np.vsplit(a,3)

[[0. 4. 4. 9. 2. 7. 9. 6. 4. 8. 2. 4.]
 [5. 8. 4. 0. 4. 2. 7. 7. 2. 5. 2. 9.]]
[array([[0., 4., 4., 9.],
       [5., 8., 4., 0.]]), array([[2., 7., 9., 6.],
       [4., 2., 7., 7.]]), array([[4., 8., 2., 4.],
       [2., 5., 2., 9.]])]
[array([[0., 4., 4.],
       [5., 8., 4.]]), array([[9.],
       [0.]]), array([[2., 7., 9., 6., 4., 8., 2., 4.],
       [4., 2., 7., 7., 2., 5., 2., 9.]])]
[[0. 6.]
 [7. 8.]
 [7. 2.]
 [0. 7.]
 [3. 9.]
 [3. 4.]
 [9. 3.]
 [0. 5.]
 [9. 3.]
 [2. 2.]
 [2. 0.]
 [9. 6.]]


[array([[0., 6.],
        [7., 8.],
        [7., 2.],
        [0., 7.]]), array([[3., 9.],
        [3., 4.],
        [9., 3.],
        [0., 5.]]), array([[9., 3.],
        [2., 2.],
        [2., 0.],
        [9., 6.]])]