In [4]:
import numpy as np
numbers = np.array([2,3,4])
print(numbers)
numbers.dtype

[2 3 4]


dtype('int32')

In [8]:
vector = np.array([5,10,15,20])
print(vector[0:3])

[ 5 10 15]


In [13]:
matrix = np.array([
    [5,10,16],
    [20,26,40],
    [34,40,46]])
print(matrix[:,1])
print(matrix[:,0:2])

[10 26 40]
[[ 5 10]
 [20 26]
 [34 40]]


In [16]:
vector = np.array([5,10,15,20])
vector== 10
equel_to_10 = (vector==10)
print(equel_to_10)
print(vector[equel_to_10])

[False  True False False]
[10]


In [17]:
vector = np.array([5,10,15,20])
equel_to_ten_and_five = (vector ==10) & (vector ==5)
print(equel_to_ten_and_five)


[False False False False]


In [20]:
vector = np.array(["1", "2", "3"])
print(vector.dtype)
vector= vector.astype(int)
print(vector.dtype)
print(vector)


<U1
int32
[1 2 3]


In [21]:
vector = np.array([5,10,15,20])
vector.min()
#print(help(np.array))


5

In [22]:
matrix = np.array([[5,10,15],
                  [24,54,55],
                  [52,45,67]])
matrix.sum(axis=1)

array([ 30, 133, 164])

In [23]:
matrix = np.array([[5,10,15],
                  [24,54,55],
                  [52,45,67]])
matrix.sum(axis=0)

array([ 81, 109, 137])